holidaycheck/tech-blog

_posts/2017-06-02-jslang-meetup-async-await.markdown

My first post on the HC blog ... now we only need to get this blog live :)

#jslang meetup post

---

_config.yml
_includes/excerpt.html
_layouts/author.html
_layouts/home.html
_layouts/post.html
_posts/2017-06-23-enterjs-es6-and-flowtype.md
_sass/_global.sass
_sass/partials/_single.sass

Polishing some details.
Many things, see the commits ...

Make the look more consistent

---

_includes/excerpt.html
_sass/_global.sass

This does some small modifications to the styling:
* Move the content so it isn't so glued to the left side bar
* Add some margin to the images displayed in the article preview

Adjust layout

---

_posts/2017-07-01-build-custom-ui-extensions-in-contentful.md

Fixes some stuff I noticed during reading the article.

Contentful Post: Fixes some links plus better wording

---

_layouts/post.html
_sass/partials/_single.sass

Text is right now more exposed.

Make more space around titles

---

_posts/2017-07-14-hc-all-devs-meetup.md

@cosimalaube I swapped the alignment of the images, so the quote rendering wont be broken.
Before it was like this:
And with this PR it would look like this:

Pretty up alldevs post

---

_posts/2017-07-14-hc-all-devs-meetup.md

- added link to hcalldev tweets
- cite Bettina for Open Space summary

Enhance HC All Devs Blogpost

---

_posts/2017-06-02-jslang-meetup-async-await.md
_posts/2017-06-30-cop-testing-2.md
_posts/2017-07-10-hc-katas.md
_posts/2017-07-14-hc-all-devs-meetup.md

the category will come alive once the #43 will be merged.

Add "learn" category to some posts

---

README.md

I think that is something we forgot to do after we went live with the blog

Update README with production url of the techblog

---

.gitignore
.travis.yml
default.nix
test.sh

- Add test.sh containing category/thumbnail consistency check
- Make project buildable with nix-build
- Add ./result symlink to gitignore
- Add travis configuration

Add tests / set up nix-build / use travis.ci

---

_posts/2017-11-01-nixcon2017.md

feel free to merge onto your branch, if you like to

Use the URLs as links.

---

_posts/2017-11-01-nixcon2017.md

Add a link to the playlist on YT

Add YT link to nixcon recordings

---

author-tobiaspflug.md

- capitalize "I"
- remove dots in list to be consistent
- change "a" to "an"
- change link to conf

Improve profile page for Tobias Pflug

---

_posts/2017-11-07-haskell-learning-group-our-progress-and-updates.md

New blog post "Haskell Learning Group: Our Progress and Updates"

Add new blog post about Haskell Learning Group

---

_includes/head.html
_layouts/default.html

Added FB, Google, Twitter metadata to display our content in more attractive way.
Followed by this article: https://moz.com/blog/meta-data-templates-123

Social media meta data

---

_posts/2017-06-02-jslang-meetup-async-await.md
_posts/2017-06-23-enterjs-es6-and-flowtype.md
_posts/2017-06-30-cop-testing-2.md
_posts/2017-07-14-hc-all-devs-meetup.md
_posts/2017-10-13-jb-in-da-house.md
_posts/2017-10-20-jbhc17-from-my-perspective.md
_posts/2017-11-01-nixcon2017.md
category/conference/index.html
category/meetup/index.html

Group "conference" and "meetup" into category "event"

---

_data/events/2017.yml
_data/events/2018.yml
_layouts/events.html
js/main.js

... and added the testing conf

Separate the events by year, add a new tab for 2018

---

_data/events/2017.yml

Andi's events

---

_config_local.yml
default.nix

This makes links and images in the local env work again.

Start the server with local config overrides.

---

_posts/2017-12-22-responsive-images-srcset-and-sizes.md

Minor change fixing a sentence containing "to fit the our customer's screen size" and removed "the".

Fixes tiny issue in post about responsive images

---

_data/events/2018.yml
_layouts/events.html

This PR contains:
- more confs and unconfs
- shows only 3 tags per event, the rest can be shown on click

Add some (un)confs for 2018

---

.github/PULL_REQUEST_TEMPLATE.md

Read more on [PR template, here](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)
- Add a PR template, to give people a hand on what to write in the PR.
- And sneak the "merge-asap" strategy into it :).
Thanks.)

Add a github-PR template

---

_data/events/2018.yml

Add busconf & monadic party
Thanks.)

Add events

---

_data/events/2018.yml

Fix socrates ch date, thx for reporting Cosima

---

_data/events/2018.yml

Add amsterdamJS (and it's CfP)
Thanks.)

Add amsterdamJS (and it's CfP)

---

_data/events/2018.yml

Add jslang meetup Feb 2018
Thanks.)

Add event: jslang meetup Feb 2018

---

_data/events/2018.yml

Add Design Systems Virtual Summit 2018, the first design focused event :)
Thanks.)

Add event: Design Systems Virtual Summit 2018

---

_data/events/2018.yml

Add 2 (un)confs

---

_includes/excerpt.html
_sass/_global.sass
_sass/partials/_excerpt.sass
_sass/partials/_single.sass

Rendering HTML in excerpt causes problems, see [commit](https://github.com/holidaycheck/tech-blog/pull/123/commits/8d744973679c9719982373e336f2be83931bad23).
Currently:
After change:
Rendering H4 tag was ... not so well done visually.
Currently:
After change:
H3 was also fixed a bit.
(checkout commits and descriptions for more detailed info)

Improve displaying

---

_posts/2018-11-08-jslang-meetup-errors
_posts/2018-11-08-jslang-meetup-errors.md

A mini post about #jslang meetup Nov 2018
Thanks.)

JSLang Meetup post

---

_data/events/2019.yml
_layouts/events.html

Adds all events I found for 2019.
Thanks.)

2019 events

---

_layouts/events.html
js/main.js

Fixes links to events in given year

Fix links to event tabs

---

_posts/2019-01-10-our-okr-process.md

I got feedback that I generalize how everyone is feeling. I think that is a fair feedback and I want to change it.

Soften my generalization about people's feelings

---

_data/events/2019.yml
default.nix

- added Frontendconf, this weekend and POznan's DevOpsDay
- added various #jslang events and the upcoming MunichJS
Thanks.)

Add more events

---

_posts/2019-05-06-browsertools#1-resource-timing-part1.md

- add another reload button to make the article more interactive
- show more precise numbers since loading on desktop is sooo fast, that numbers don't differ
Thanks.)

Improve browsertools #1

---

_sass/_type.sass

It is to get ready for https connection.

Have google font be loaded protocol-agnostic

---

_posts/2019-05-06-browsertools#1-resource-timing-part1.md

- This change really determines the maximum of a number-array (in contrast to `sort()` function, which sorts items lexicographically, even numbers!)
Thanks.)

Determination of the largest element

---

_posts/2019-05-06-browsertools#1-resource-timing-part1.md

Fixes what #161 tried to fix too, but simpler.
- sorts the numbers in the browsertools #1 blog post correctly
Thanks.)

Fix the sorting to be numeric not alphanumeric.

---

_posts/2019-05-06-browsertools#1-resource-timing-part1.md

This makes reading more fluent and sets a better end to the article.
Thanks.)

Polishing browsertools #1

---

_posts/2019-05-06-browsertools#1-resource-timing-part1.md

Markusheilig's fixes performance post #1

---

_data/events/2019.yml

Add more confs+meetups
